### ISSUE TITLE
pytest failures (with 4.2.1)

### ISSUE THREAD

**Issue by CMCDragonkai** [carsonfarmer/fastpair#14]
Latest pytest fails on this repository.

Complains:

```
Fixture "PointSet" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
```

Fixture code should be updated.

**Comment by carsonfarmer** [comment]
I'm unable to devote much time to this package these days. If you would like to submit a PR for this, I would be happy to accept!

**Comment by CMCDragonkai** [comment]
I've forked it into my client's org. But you haven't submitted this on PyPi? Do you mind if I submit it from our fork then?

**Comment by carsonfarmer** [comment]
Sure, go for it. But could you also submit a PR from your fork to this one, just so I have your updates? We could also add a link to the README indicating that it has been uploaded to pypi via your clients org?

**Comment by Rakesh4G** [comment]
I have started on this issue.

**Comment by carsonfarmer** [comment]
Thanks!
