### ISSUE TITLE
rename branches: `master` for `main`?

### ISSUE THREAD

**Issue by jGaboardi** [carsonfarmer/fastpair#21]
@carsonfarmer before works start on modernization, would it be possible to rename branches: `master` for `main` for [more inclusive language](https://sfconservancy.org/news/2020/jun/23/gitbranchname/), as we have done over in the PySAL ecosystem -- https://github.com/pysal/pysal/issues/1285?

**Comment by carsonfarmer** [comment]
yeh sure
