### ISSUE TITLE
[INFRA] tag `fastpair==0.1.0` causing on issue on install

### ISSUE THREAD

**Issue by jGaboardi** [carsonfarmer/fastpair#29]
While working on (3.) in https://github.com/carsonfarmer/fastpair/issues/20, I am running into the problem of there being no associated [*dynamic* version](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#version) with the [`fastpair==0.1.0` tag](https://github.com/carsonfarmer/fastpair/releases/tag/fastpair%3D%3D0.1.0), which is causing the `pip install -e .` to fail.

The two options (IMHO) are a conservative approach [1,2] or a more aggressive approach [2] that does it all at once.

1. conservative approach (2 PRs):
   1. explicitly declaring `version = "v0.1.0"` in `pyproject.toml` in a first PR addressing (3.)
   2. (perhaps create a `v0.1.1` tag and associated release, but this might be overkill)
   3. proceed to step 2
2. one stroke (1 PR):
   1. delete the `fastpair==0.1.0` tag (remote & local)
   2. declare `dynamic = ["version"]` in `pyproject.toml`

@carsonfarmer Let me know if (A) you have any questions/concerns here; and (B) which approach you'd like me to take.

**Comment by carsonfarmer** [comment]
Since we didn't have tags and releases before, I don't see any reason not to just go with **option 2**. But I'm happy to adopt either, I leave it up to you.

**Comment by jGaboardi** [comment]
I'll go with option 2.
