### ISSUE TITLE
update `README` by section

### ISSUE THREAD

**Issue by jGaboardi** [carsonfarmer/fastpair#35]
update `README` by section

* [x] Overview
* [x] Installation
* [x] Testing
* [ ] Features -- move to a notebook?
* [ ] License -- anything here?

**Comment by carsonfarmer** [comment]
The only requirement on license is that it should remain MIT, given the original sources that I consulted.

**Comment by jGaboardi** [comment]
> The only requirement on license is that it should remain MIT, given the original sources that I consulted.

Will leave as is.
