### ISSUE TITLE
move `Features` to notebook?

### ISSUE THREAD

**Issue by jGaboardi** [carsonfarmer/fastpair#38]
@carsonfarmer How do you think about having the `Features` section of the `README` moved from there into a notebook? If that sounds like a good idea, would we want that directory to be named:
* [x] `notebooks/`
* [ ] `examples/`
* [ ] `demos/`
* [ ] something else?

xref #20, #35

**Comment by carsonfarmer** [comment]
Sounds like a great idea. I checked notebooks, because this seems like something someone might be looking for? But `examples/` seems equally useful? So no preference really.

**Comment by jGaboardi** [comment]
Most PySAL packages use `notebooks/`. We'll go with that.

**Comment by jGaboardi** [comment]
As for the `merge_closest()` example (xref #34) in the *Features* section, I'm supposing that it should not be present in the example notebook (at least for the present)?

**Comment by carsonfarmer** [comment]
> I'm supposing that it should not be present in the example notebook (at least for the present)?

Yes I think that's probably a good idea.

**Comment by jGaboardi** [comment]
closed via #40
